version: '3.7'
services:
  redis:
    container_name: redis
    image: 'redis:alpine'
    command: redis-server
    ports:
      - '6379:6379'

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: general
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
